In [2]:
from sklearn.datasets import load_iris
iris=load_iris()

In [3]:
x=iris.data# x is a array
y=iris.target
x.shape

(150, 4)

In [4]:
import pandas as pd
pd.DataFrame(x).head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# import,initiate ,fit ,predict  four steps in basic modeling

In [7]:
#in scikit learn we change the parameters during intializing

In [8]:
# scikit learn is built on top of numpy

In [9]:
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [10]:
#count vectorizer
#convert text into numbers for nlp
# convert text into a matrix of token counts
# import ,initiate,fit,transform for cout vectorizer


In [11]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [12]:
vect.get_feature_names()
# these are the  words it learned

['cab', 'call', 'me', 'please', 'tonight', 'you']

In [13]:
sp=vect.transform(simple_train)
vect.transform(simple_train).toarray()# this is our representation 
#of text in numerical  data

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

Each individual token occurrence frequency (normalized or not) is treated as a feature.
The vector of all the token frequencies for a given document is considered a multivariate sample.
A corpus of documents can thus be represented by a matrix with one row per document and one column
per token (e.g. word) occurring in the corpus.

In [14]:
type(sp)

scipy.sparse.csr.csr_matrix

In [15]:
sp

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [16]:
print(sp)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


count vectorizer gives sparse matrix

bag of words model dosent have any meaning or
sequence of the words jjust it has a word or it doesnt have the word

In [17]:
simple_test=["please don't call me"]
simple_test_dtm=vect.transform(simple_test)# dtm= document token matrix
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [18]:
#we fit ,transform the trainig data
# we only transform the test data
# by doing we convert text to numbers and can be used for modelling

In [19]:
data=pd.read_table('sms.tsv',header=None)
data.columns=['label','mail']

In [20]:
data.head()

label                                               mail
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [21]:
data.shape
data.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [22]:
data.label=data.label.map({'ham':0,'spam':1})

In [23]:
data.head()

label                                               mail
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [24]:
data.label.shape

(5572,)

In [37]:
x=data['mail']
y=data['label']
from sklearn.cross_validation import train_test_split
trainx,testx,trainy,testy=train_test_split(x,y)
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()
trainx=vect.fit_transform(trainx)# this is trainxdtm
testx=vect.transform(testx)

In [39]:
%time trainx.shape

Wall time: 0 ns


(4179, 7476)