In [12]:
q= [
[0, 0, 4, 0, 8, 0, 3, 0, 0],
[0, 0, 0, 0, 0, 3, 0, 4, 2],
[8, 0, 0, 4, 0, 5, 9, 0, 7],
[3, 0, 2, 0, 7, 0, 5, 0, 8],
[0, 5, 0, 0, 0, 0, 0, 7, 0],
[6, 0, 8, 0, 9, 0, 2, 0, 1],
[4, 0, 6, 2, 0, 7, 0, 0, 9],
[5, 2, 0, 9, 0, 0, 0, 0, 0],
[0, 0, 7, 0, 1, 0, 4, 0, 0]
]
import numpy as np
q=np.array(q)

In [8]:
import numpy as np
q=np.array(q)
q[2,:]#row
q[:,2]#column
np.unique(list(np.unique(q[0,:]))+list(np.unique(q[:,1])))

array([0, 2, 3, 4, 5, 8])

In [31]:
q1=q
for k in range(10000):
    for i in range(9):
        for j in range(9):
            if q[i][j]!=0:
                continue
            if i<3 and j<3:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[0:3,0:3]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<3 and j>3 and j<6:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[0:3,3:6]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<3 and j>6 and j<9:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[0:3,6:9]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<6 and i>3 and j<3:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[3:6,0:3]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<6 and i>3 and j<6 and j>3:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[3:6,3:6]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<6 and i>3 and j<9 and j>6:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[3:6,6:9]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<9 and i>6 and j<3:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[6:9,0:3]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<9 and i>6 and j<6 and j>3:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[6:9,3:6]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
            if i<9 and i>6 and j<9 and j>6:
                l=list(set(range(1,10))-(set(np.unique(list(np.unique(q[6:9,6:9]))+list(np.unique(q[i,:]))+list(np.unique(q[:,j]))-set([0])))))
                if len(l)==1:
                    q[i][j]=l[0]
                continue
        
print(q)
        
    
    


[[2 8 4 0 9 3 0 6 7]
 [3 6 9 4 7 1 0 2 5]
 [1 5 7 8 2 6 0 9 3]
 [0 0 6 0 0 0 0 3 1]
 [8 9 2 1 3 5 6 7 4]
 [4 1 3 0 6 7 9 5 8]
 [7 0 0 0 8 0 0 4 6]
 [6 4 5 0 1 2 0 8 9]
 [9 3 8 0 5 4 7 1 2]]


In [ ]:
[[2, 8, 4 ,0 ,9, 3, 0, 6, 7],
 [3, 6, 9, 4, 7, 1, 0, 2, 5],
 [1 ,5 ,7, 8 ,2 ,6, 0 ,9, 3],
 [0 ,0 ,6 ,0 ,0 ,0 ,0 ,3 ,1],
 [8 ,9 ,2 ,1 ,3 ,5 ,6 ,7 ,4],
 [4 ,1 ,3 ,0 ,6 ,7 ,9 ,5 ,8],
 [7 ,0 ,0 ,0 ,8 ,0 ,0 ,4 ,6],
 [6 ,4 ,5 ,0 ,1 ,2 ,0 ,8 ,9],
 [9 ,3, 8 ,0 ,5 ,4 ,7 ,1 ,2]]

q

In [15]:
q

array([[2, 0, 4, 0, 8, 0, 3, 0, 0],
       [7, 0, 0, 0, 6, 3, 0, 4, 2],
       [8, 0, 0, 4, 2, 5, 9, 0, 7],
       [3, 0, 2, 0, 7, 0, 5, 0, 8],
       [1, 5, 9, 0, 3, 0, 0, 7, 0],
       [6, 7, 8, 0, 9, 4, 2, 3, 1],
       [4, 0, 6, 2, 0, 7, 0, 0, 9],
       [5, 2, 0, 9, 4, 0, 0, 0, 0],
       [9, 0, 7, 0, 1, 0, 4, 0, 0]])

In [20]:
s=[[ 0, 0, 4,   0, 0, 0,   0, 6, 7 ],
                        [ 3, 0, 0,   4, 7, 0,   0, 0, 5 ],
                        [ 1, 5, 0,   8, 2, 0,   0, 0, 3 ],
                            
                        [ 0, 0, 6,   0, 0, 0,   0, 3, 1 ],
                        [ 8, 0, 2,   1, 0, 5,   6, 0, 4 ],
                        [ 4, 1, 0,   0, 0, 0,   9, 0, 0 ],
                            
                        [ 7, 0, 0,   0, 8, 0,   0, 4, 6 ],
                        [ 6, 0, 0,   0, 1, 2,   0, 0, 0 ],[ 9, 3, 0,   0, 0, 0,   7, 1, 0 ]]
np.array(s)

array([[0, 0, 4, 0, 0, 0, 0, 6, 7],
       [3, 0, 0, 4, 7, 0, 0, 0, 5],
       [1, 5, 0, 8, 2, 0, 0, 0, 3],
       [0, 0, 6, 0, 0, 0, 0, 3, 1],
       [8, 0, 2, 1, 0, 5, 6, 0, 4],
       [4, 1, 0, 0, 0, 0, 9, 0, 0],
       [7, 0, 0, 0, 8, 0, 0, 4, 6],
       [6, 0, 0, 0, 1, 2, 0, 0, 0],
       [9, 3, 0, 0, 0, 0, 7, 1, 0]])